PERFORMANCE, README, src/modules/database/CPU.c, src/modules/database/p_database.h, src/modules/exploit_detection/p_exploit_detection.c, src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.c, src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.h, src/modules/integrity_timer/p_integrity_timer.c, src/modules/kmod/p_kmod.c
Spelling PR as suggested by @solardiz
=> Various spelling and grammar corrections

src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
=> Log file permissions in octal format

README
=> ADDED CORRECT REPOSITORY TO CLONE FROM IN README

.github/PULL_REQUEST_TEMPLATE.md
This will help us to document what was changed and what
tests we have run.
=> github: Add a pull request template

scripts/copy-builtin.sh
=> Copy-builtin: use bash and correct depends

scripts/bootup/lkrg-bootup.sh
=> Improve shell script

scripts/bootup/lkrg-bootup.sh, scripts/bootup/systemd/lkrg-systemd.sh
scripts: do not use P_PWD
lkrg-bootup.sh: exec P_LKRG_SYSTEMD
scripts: double-quote variables and expansions, copy file with archive mode
=> Improve scripts

README
Made a few minor changes, particularly to punctuation, but also to word choice and word flow. For example, "might or might not" is more uncomfortable to say and read than "may or may not" as the ending "t" requires a stop. I believe these changes **may** (heh) increase readability marginally. I also did not go through and check the commands and their descriptions.
However, in regards to the manual testing portion, I believe it is still better, but rather awkward to read. Give me a few minutes and I can improve it further with some restructuring. I did this on my phone, so I would prefer to first switch to my PC for further changes.
This requires no testing as it is just minor updates to the README.
=> Fixed punctuation, word choice, and word flow

debian/changelog, debian/copyright, debian/lkrg-dkms.sysctl
Here are the changes for the upcoming LKRG release. Basically all that's needed is just to bump the version number in the `debian/changelog` file, and add the line saying `* New upstream release.`
I also included the missing copyrights and added the LKRG sysctl documentation in the sysctl file (it was taken from the README file) so everything was in one place when a user wants to change any of the parameters.
=> Update for the debian/ dir

debian/control
https://github.com/openwall/lkrg/issues/108#issuecomment-890534005
=> stop recommending lkrg-systemd

src/modules/exploit_detection/p_exploit_detection.h
Linked to https://github.com/openwall/lkrg/pull/123#pullrequestreview-805474621
=> p_exploit_detection.h: add braces to preprocessor conditions

.github/workflows/mkosi-boot.yml, .github/workflows/mkosi-mainline.yml
This is supposed to fix #129. Let's wait and see.
=> CI: mkosi-*: Update expected Power Off target regexp

.github/workflows/mkosi-mainline.yml
=> CI: Do not schedule Github actions in forks

src/modules/exploit_detection/p_exploit_detection.h, src/p_lkrg_main.h
This is an attempt at fixing #145. Totally untested - this PR is to test it via CI.
=> Fix build on CentOS Stream 9

.github/workflows/mkosi-boot.yml, .github/workflows/mkosi-mainline.yml
As discussed in https://github.com/lkrg-org/lkrg/issues/132
Tested: https://github.com/vt-alt/lkrg/actions/runs/1884073929 all OK.
While testing there was failure on `jammy`: https://github.com/vt-alt/lkrg/runs/5294495248?check_suite_focus=true I don't know if it's related to LKRG, and it's disappeared on next run.
```
[   12.240310] BUG: kernel NULL pointer dereference, address: 0000000000000000
```
=> CI: Add Bionic and fix KVM misdetection 

Makefile
Instead of comment add proper option to build LKRG with debug.
$ make | grep debug
$ make DEBUG=on | grep debug
=> make: introduce an option to build LKRG with debug

README
Added instructions on how to install lkrg using DKMS
Tested on Fedora 36 switching between kernels
=> Added instructions on how to install lkrg using DKMS

.github/workflows/codeql-analysis.yml
Added `codeql-analysis.yml` to enable code scanning workflow.
This configuration only allows to run the default set of queries, but custom queries can be added in the future.
Tested with several artificial examples.
=> Enable code scanning with CodeQL

src/modules/notifiers/p_notifiers.c
Reported-by: Alexey Gladkov <legion@altlinux.ru>
Signed-off-by: Vladimir D. Seleznev <vseleznv@altlinux.org>
=> Add support for RHEL 9.2 kernel

src/modules/exploit_detection/p_exploit_detection.c, src/modules/exploit_detection/p_exploit_detection.h, src/modules/exploit_detection/syscalls/p_do_exit/p_do_exit.c, src/modules/exploit_detection/syscalls/p_wake_up_new_task/p_wake_up_new_task.c
As discussed with @kerneltoast in comments starting with https://github.com/lkrg-org/lkrg/issues/385#issuecomment-2869538143
Built, loaded. Not much testing done yet.
=> No shadow task update on new task wake-up
