lkrg-org/lkrg

- src/p_lkrg_main.h
Consequence of compiling for ARMv8 on ALT.
```
Due to kernel commit f3ac60671954c ("sched/headers: Move task-stack
related APIs from <linux/sched.h> to <linux/sched/task_stack.h>") (Linux
v4.11) `linux/sched/task_stack.h' should be included to access
`task_stack_page'.
```
> Fix implicit declaration of function 'task_stack_page' on arm

- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
- src/modules/kmod/p_kmod.c
- src/p_lkrg_main.c
- src/p_lkrg_main.h
1. `file` is no longer a field in the `subprocess_info` struct, so we just don't use it.
2. `__module_address` and `__module_text_address` are no longer exported, so we need to resolve these symbols at runtime.
3. `put_seccomp_filter` has been removed, so we need to use `__put_seccomp_filter` instead and modify calls to this function.
My understanding on LKRG's code is very limited, so please check this for errors. With these fixes I managed to build LKRG against 5.9.0 and it reports successful initialization when it is loaded.
> Fix building on Linux 5.9

- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
When we detect an invalid binary, we forbid it execution by changing the
subprocess execution path with slashes.
On some kernels, this may not work because we have to map the memory page as
writable. At this moment of execution, we can stop executing the process using
the froce_sig to send signals. The send_sig_info will not arrive at the right
time.
This should fix [Issue 4](https://github.com/openwall/lkrg/issues/4)
> umh: Kill process using the proper SIGKILL signal.

- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.h
- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_usermode_kernel_dep.h
UMH contains a list of files that are allowed to execute.
LKRG during the load checks if the file exists; if so, the file is added to
the whitelist. The umh_preexists_files allows controlling this check.
By disabling lkrg.umh_prexists_files sysctl, all the files from the
lists will be allowed no matter if they were created after LKRG was loaded.
> UMH: Allow all the pathnames listed in p_umh_global

- scripts/copy-builtin.sh
DKMS is not always desirable on a system which one intends to
harden from local attackers. The build-chain creates a wide local
attack surface and can be used to build kmode rootkits and other
fun toys for red team. There are also space, performance,
and security considerations such as leaving RANDSTRUCT seeds
around in headers which can be addressed by bringing the module
in with the kernel package.
In order to avoid this, and take advantage of pending advances
in LTO, KCFI, and other methods depending on or benefitting from
having all of the code available at initial compile/link-time, a
script has been added to update the desired kernel tree with the
LKRG source code and relevant Makefile and Kconfig directives.
Since LKRG is still in active development, this script pulls all
relevant …
> Build LKRG in-tree using copy-builtin.sh

- scripts/copy-builtin.sh
After 58b9ec06, the script which copies module files into the
kernel source tree does not properly capture the files to be built
into p_lkrg.o.
Fix the awk expression performing the capture to adjust for the
new `$(TARGET)-obj` syntax and sed in-place to restore the original
name for in-tree build.
> In-tree: fix for 58b9ec06

- src/modules/exploit_detection/p_exploit_detection.h
There are unofficial versions of RANDKSTACK patches floating about
the web, including in VMWare's PhotonOS.
The randomized stack addresses conflict with LKRG's ADDR_LIMIT
checks a la:
```
[  195.272462] [p_lkrg] <Exploit Detection> Detected ADDR_LIMIT
segment corruption! process[552 | sysctl] has different segment
address! [7ffffffff000 vs ffffffffffffffff]
```
Address this by ensuring that P_VERIFY_ADDR_LIMIT does not get
defined when CONFIG_PAX_RANDKSTACK is enabled.
This is a strange edge-case, and normally wouldn't be submitted as
a pull request to upstream projects, except that users seeking to
harden their kernels with public code are likely to run across
LKRG and some links to the PhotonOS patches or similar extracts
from Grsecurity's old patchsets. The commit is a no-op in 99% of …
> CONFIG_PAX_RANDKSTACK ^ P_VERIFY_ADDR_LIMIT

- scripts/copy-builtin.sh
If the source tree is not a git repository or git is not installed,
avoid throwing errors.
If the source tree to copy LKRG to as a built-in is not a git repository or git is not installed on the machine, errors are thrown although the install is a success. This commit checks for these prerequisites before trying to commit changes to a git repository.
The script was modified and run on both a machine with git installed but the source tree was not a git repository, as well as a machine where git was installed and the source tree was also a repository. In both cases no errors were thrown from the script and the copying of LKRG as a built-in was a success.
> copy-builtin: avoid errors when committing changes

- scripts/copy-builtin.sh
Some systems do not have the git binary or in the current PATH.
Concurrently, some users do not have git source control for LKRG
or their kernel tree, making the assumptive git commands useless.
Address by way of conditional checking for presence of the git bin
in the current PATH as well as the existence of a git revision in
the CWD.
> Copy-builtin: address lack of git or .git

- src/modules/exploit_detection/p_exploit_detection.h
Since kernel commit 3d2403fd10a1dbb359b154af41ffed9f2a7520e8 there is no
more addr_limit on arm64.
> Fix compilation fo kernel 5.11 on arm64

- scripts/copy-builtin.sh
This fixes the following error when using bash:
bash: [: missing `]'
> copy-builtin: fix syntax error

- Makefile
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/exploit_detection/p_selinux_state.c
- src/modules/exploit_detection/syscalls/p_sel_write_enforce/p_sel_write_enforce.c
- src/p_lkrg_main.h
* Rework the SELinux architecture.
Separate SELlinux to a new file
Introduce API for SELinux related orations.
Deduplicat code.
* Add support for kernels with rand structs (CONFIG_GCC_PLUGIN_RANDSTRUCT option).
In this case we disable SELinux monitoring.
* Add support for kernels newer then 5.6 the (CONFIG_SECURITY_SELINUX_DISABLE option)
Reflect changes in the selinux_status struct.
On ubuntu machine with custom 5.11.6 kernel build.
I used p_vuln to implement overwriting the selinux_status struct fields, and checked if the kernel will panic and if the original value will be restored.
> Rework selinux architecture

- .github/workflows/mkosi-boot.yml
- .gitignore
- mkosi.build
- mkosi.default
- mkosi.postinst
There are two commits:
```
Author: Vitaly Chikunov <vt@altlinux.org>
Date:   Mon Mar 29 06:37:51 2021 +0300
Add mkosi support
mkosi is systemd's boot test tool. This support is mainly for GA CI
to implement full boot tests (on Ubuntu). But, this would be useful
on it's own for experiments with lkrg on all mkosi supported distros.
I support only bios (grub) BottProtocol without unified kernel.
- .gitignore updated to exclude mkosi artifacts (otherwise they could
recursively go into created image causing disk full error).
- mkosi.default is mkosi config pre-confirured for ubuntu focal, you can
overwrite this with command line options.
- mkosi.build is script to build lkrg and install it into DESTDIR.
- mkosi.postinst hook updates initrd to include and insmod lkrg and
grub to remove 'quiet' …
```
> mkosi and GA CI support for boot test on Ubuntus

- .github/workflows/dpkg-i.sh
- .github/workflows/mkosi-mainline.yml
- .github/workflows/ubuntu-kernel-daily.sh
- .gitignore
- mkosi.build
- mkosi.default
- mkosi.postinst
```
Ubuntu have daily builds of mainline kernels at
https://wiki.ubuntu.com/Kernel/MainlineBuilds
They are built on groovy.
```
Example actions https://github.com/vt-alt/lkrg/actions
I decided to create 2 workflows (instead of single one with 3 element matrix, that I tried too), (**pros**) because -- this will allow to disable one of workflows (for example mainline one) from GA web UI; and allows to run mainline workflow also from cron schedule (daily). -- (**cons**) This will create two "lines" in Actions for every commit -- this is bad UI design, because single run is not grouped, but cant be helped (every other repo with complex workflows have that); and this is code duplication, but this is overall style of GA and cant be helped too.
I don't understand completely who will receive …
> CI: Boot test using Ubuntu mainline kernel build

- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- Add '\n' to `send_error' so the (timeout) error message is not lost.
Otherwise, we see just "Error: Process completed with exit code 1."
- Add `-no-reboot' qemu option so the system does not cycle after first
kernel panic (burying error message).
Improves on issues found in #62.
> CI: Improve mkosi testing (`-no-reboot`)

- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- mkosi.default
On 22 Apr 2021 Ubuntu released Hirsute Hippo (21.04) and started
building mainline kernels next day on it, causing mkosi builds fail
on 'groovy' with:
dpkg: dependency problems prevent configuration of linux-headers-5.12.0-051200rc8daily20210423-generic:
linux-headers-5.12.0-051200rc8daily20210423-generic depends on libc6 (>= 2.33); however:
Version of libc6:amd64 on system is 2.32-0ubuntu3.
Also, update workflows and 'mkosi.default' to use 'hirsute'.
Tested, all green: https://github.com/vt-alt/lkrg/actions # 8 and 49.
> CI: Update mkosi builds with 'hirsute'

- scripts/bootup/lkrg.conf
- scripts/bootup/systemd/lkrg-systemd.sh
- scripts/bootup/systemd/lkrg.service
lkrg-helper is aimed to help service manager to start and stop lkrg
service. Its main purpose to store and restore lkrg settings state
during service restart. It is designed to be service manager agnostic.
This commit also introduces a new semantic for systemctl reload that
restores lkrg default settings.
* libexec/lkrg-helper: New file.
* systemd/lkrg-systemd.sh: Install lkrg-helper.
* systemd/lkrg.service: Use lkrg-helper; add new semantic for reload
that restores default lkrg settings.
> Enhance systemd service, introduce lkrg.conf

- .github/workflows/ubuntu-kernel-daily.sh
Sometimes there are no kernel-ppa/mainline packages on the day even if
`amd64' dir exists, skip to the next day.
Should fix build error reported by @solardiz at https://github.com/openwall/lkrg/pull/83#issuecomment-840084388
> CI: Fix download of the mainline kernel

- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- Fix grep negation for the 'mkosi-boot' test.
- Also, change 'Panic' to 'Kernel panic' the way it should be.
> CI: Fix grepping for the kernel panics

- dkms.conf
This simple `dkms.conf` file provides support for DKMS. To build LKRG using pure DKMS, you have to copy the LKRG source to the `/usr/src/lkrg-0.9.1/` and issue the following command:
```
Creating symlink /var/lib/dkms/lkrg/0.9.1/source ->
/usr/src/lkrg-0.9.1
DKMS: add completed.
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:
make -C /lib/modules/5.12.4-amd64/build M=/var/lib/dkms/lkrg/0.9.1/build clean
make: Entering directory '/usr/src/linux-headers-5.12.4-amd64'
make: Leaving directory '/usr/src/linux-headers-5.12.4-amd64'
{ make -j4 KERNELRELEASE=5.12.4-amd64 -C /lib/modules/5.12.4-amd64/build M=/var/lib/dkms/lkrg/0.9.1/build; } >> /var/lib/dkms/lkrg/0.9.1/build/make.log 2>&1
Running the post_build script:
Signing kernel_object: p_lkrg.ko
make -C …
```
> Add support for building LKRG via DKMS

- CHANGES
- src/modules/database/FTRACE/p_ftrace_modify_all_code/p_ftrace_modify_all_code.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/TRACEPOINT/p_arch_static_call_transform/p_arch_static_call_transform.c
- src/modules/kmod/p_kmod.c
- src/p_lkrg_main.c
- src/p_lkrg_main.h
This is supposed to fix #93, but is not tested yet.
> Support unexporting of __module_address* by Linux 5.4.118+

- scripts/bootup/systemd/lkrg-systemd.sh
The systemd install script attempts to enumerate the proper location to install the LKRG unit to, which in its current state may lead to inconsistencies. Instead, the unit should be installed into `/etc/systemd/system` unconditionally, as this is the standard location for user-installed system units.
Issued a `make install` and verified that the unit was installed to `/etc/systemd/system`.
Closes #95
> Install systemd unit to /etc/systemd/system unconditionally

- .github/workflows/builds.yml
Test build on Fedora, CentOS, and ALT.
https://github.com/openwall/lkrg/pull/61#issuecomment-813011209
> I think we should keep Ubuntu, but also add perhaps CentOS 7 and 8. Instead of CentOS 8, it can be (and will eventually have to be) AlmaLinux or (later) RockyLinux. Can also have Fedora or CentOS Stream - would probably let us catch issues (typically back-ports that LKRG needs to adapt to) before they appear in a RHEL/CentOS/AlmaLinux/RockyLinux release.
> CI: Build on different OS using Docker containers

- CHANGES
- src/modules/database/FTRACE/p_ftrace_modify_all_code/p_ftrace_modify_all_code.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/TRACEPOINT/p_arch_static_call_transform/p_arch_static_call_transform.c
- src/modules/kmod/p_kmod.c
- src/p_lkrg_main.h
Deduplicate use of __module_text_address.
Add more kernels where the unexported __module_address.
Build and loaded on 5.8.0-45
This should solve #100
> Fix LKRG builds on new kernels

- src/modules/exploit_detection/p_exploit_detection.h
In the c6d93ae9df2519a66a6d5ec9e226f8458c51815c we mentioned that
the task_struct had been changed, but actually the change is since
5.14. The task_struct structure is the same still in 5.13.4.
Source:
https://elixir.bootlin.com/linux/v5.13.2/source/include/linux/sched.h#L666
https://elixir.bootlin.com/linux/v5.13.3/source/include/linux/sched.h#L666
https://elixir.bootlin.com/linux/v5.13.4/source/include/linux/sched.h#L666
https://elixir.bootlin.com/linux/v5.14-rc1/source/include/linux/sched.h#L669
Build on:
`
Linux lkrg-ubu 5.13.2-051302-generic #202107141437 SMP Wed Jul 14 18:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`
> Fix building kernel 5.13.X line.

- scripts/bootup/systemd/lkrg.service
To fix Debian lintian warning.
```
I: lkrg-systemd: systemd-service-file-missing-documentation-key lib/systemd/system/lkrg.service
N: 
N:    The systemd service file does not contain a Documentation key.
N:    
N:    Documentation for systemd service files can be automatically viewed
N:    using systemctl help servicename if this field is present.
N:    
N:    Refer to the systemd.unit(5) manual page for details.
N:    
N:    Severity: wishlist, Certainty: certain
N:    
N:    Check: systemd, Type: binary
N:
```
> add Documentation=https://www.openwall.com/lkrg/

- debian/files
Why?
* It's superfluous.
* I don't remember seeing it in other packages.
* Its content are versioned. Unnecessary maintenance overhead to keep updated.
* Its contents change during build using debuild.
* Its contents are autogenerated.
> delete superfluous file debian/files

- src/modules/exploit_detection/p_exploit_detection.h
Since torvalds/linux@8ac6f5d7f84bf362e67591708bcb9788cdc42c50 there is
no addr_limit member on arm.
> Fix build for kernel 5.15 on arm

- mkosi.default
Mkosi authors decided to add `loglevel=4' to the kernel boot parameters
in systemd/mkosi@fac7bf9 ("Set loglevel to something sane when
--qemu-headless is set") this was breaking mkosi based tests.
Fixes: #126
https://github.com/vt-alt/lkrg/actions/runs/1476463050
> CI: Fix builds on newer mkosi (v10+)

- debian/rules
- scripts/bootup/systemd/lkrg-systemd.sh
- scripts/bootup/systemd/lkrg.service
https://github.com/openwall/lkrg/blob/main/debian/rules#L22 install [`scripts/bootup/lkrg.conf`](https://github.com/openwall/lkrg/blob/main/scripts/bootup/lkrg.conf) it to `/etc/sysctl.d/30-lkrg-dkms.conf`.
(The prefix `30-lkrg` seems right for a `d.` directory, i.e. for `/etc/sysctl.d/`.)
Not to `/etc/sysctl.d/lkrg.conf` as referenced in [`scripts/bootup/systemd/lkrg.service`](https://github.com/openwall/lkrg/blob/main/scripts/bootup/systemd/lkrg.service).
So in order to fix the Debian package (make LKRG work after installation) some change is required.
Currently this issue is happening:
```
user@localhost:~$ sudo systemctl status lkrg
```
```
● lkrg.service - Linux Kernel Runtime Guard
Loaded: loaded (/lib/systemd/system/lkrg.service; enabled; vendor preset: enabled)
Active: failed …
```
> fix path to /etc/sysctl.d/30-lkrg-dkms.conf

- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
Some distributions haven't merged /usr yet, so add the alternative
path for systemd-coredump.
Signed-off-by: John Helmert III <ajak@gentoo.org>
Add another path where systemd-coredump might be found to the UMH whitelist. This alternative path is already included for systemd-cgroups-agent, so adding the same for systemd-coredump should be reasonable.
With a vanilla lkrg-0.9.2, coredumps never appear and are blocked:
```
[  463.522397] [p_lkrg] Blocked usermodehelper execution of [/lib/systemd/systemd-coredump]
```
With my patch, coredumps are successful and accessible via systemd-coredump.
> Add non-usr-merged systemd-coredump to UMH whitelist

- src/modules/exploit_detection/p_exploit_detection.h
Apparently, the rename of state to __state from Linux 5.14+ has just been back-ported to CentOS Stream 8 starting with 4.18.0-349.el8 and will be in RHEL 8.6+.
Fixes #141
> Fix build on latest CentOS Stream 8 and upcoming RHEL 8.6+

- .github/workflows/builds.yml
- .github/workflows/cross.yml
- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- mkosi.build
- mkosi.default
* Do not download 200MB `linux-firmware` for mkosi tests. (I also created [issue in mkosi upstream](https://github.com/systemd/mkosi/issues/884).)
* Let `mkosi.build` be runnable manually.
* Build testing renamed from `Multi-OS container builds` to `docker build` (will be visible in Actions tab).
* More distributions added experimentally, but some can removed if not needed. (For example centos 8 clones, or openSUSE).
Also, there is compilations problems on centos9 and leap: https://github.com/vt-alt/lkrg/actions/runs/1703686921
> CI: Various improvements, add more distributions to build test

- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
SUSE version `#if`s added to a set in a similar way as RHEL.
`CONFIG_SUSE_PRODUCT_CODE` `1` seems to be for Leap, `3` for Tumbleweed.
> Fix build on opensuse/leap

- .github/workflows/mkosi-mainline.yml
As discussed in https://github.com/lkrg-org/lkrg/issues/137
>  It might be useful to always enable P_LKRG_JUMP_LABEL_STEXT_DEBUG on mainline build.
https://github.com/vt-alt/lkrg/runs/5013353445
> CI: Enable P_LKRG_JUMP_LABEL_STEXT_DEBUG in mainline test

- .github/workflows/builds.yml
Centos 8 is not meant to be officially supported after 2021-12-31.
We already have Rocky Linux and AlmaLinux instead.
As discussed in https://github.com/lkrg-org/lkrg/pull/154#issuecomment-1026389127
> CI: Remove official Centos 8 docker build test

- scripts/builtin/export_symbols_from_optimized_kernels.diff
Custom kernels compiled with -O3 (or other optimization) appear to
break the runtime symbol resolution in LKRG, as per Adam's comment:
github.com/lkrg-org/lkrg/issues/135#issuecomment-1018693257
In order to maintain access to these symbols in the optimized O3
binary, explicit export annotations are required in the kernel at
build-time.
Implemented exports for do_seccomp, change_page_attr_set_clr, and
do_seccomp on 5.10.98-hardened. Extracted the resulting diff into
the scripts/builtin directory of this repo for application by users
who patch their own kernels already. This won't help people pulling
pre-built binaries out of repositories, but AUR users and similar
compile-on-demand setups should be able to add the diff to their
PKGBUILD/analogous build blueprint.
Testing:
Arch Linux VM on …
> Add kernel diff (5.10) to export seccomp symbols

- scripts/add-exports.sh
Implements fixes from #161 via `echo` method proposed by @solardiz 
It hasnt, per se, but the original diff from which the lines `echo`d originate works like a charm
> Add explicit critical function exports to kernel sources via shell script

- scripts/copy-builtin.sh
Cleanup the copy script per @solardiz to remove pushd/popd calls since they're not needed.
Has not been tested, can't see how it could blow up
> copy-builtin.sh: Drop unneeded pushd/popd

- src/modules/database/arch/x86/p_x86_metadata.c
- src/modules/database/arch/x86/p_x86_metadata.h
This fixes #159 and cleans up the code a little.
With these changes, LKRG in the old Xen PV setup appears to work fine. Previously, it crashed.
Further, all of out GitHub Actions tests passed (under my personal GitHub account).
However, I did not test on 32-bit x86, and I think we lack such tests in CI. Ideally, we'd also test that, because the cleanup commit replaces a 32-bit specific piece with a new shared one.
> Improve x86 IDT dumping

- src/modules/exploit_detection/p_exploit_detection.c
Fixes #170
This completes changes made earlier, which inadvertently kept using `mm_segment_t` even on kernels where we don't need that.
CI is all-green in my fork of the repo.
> Fix build on post-5.17 kernels (avoid usage of mm_segment_t)

- src/modules/exploit_detection/syscalls/exec/p_security_bprm_committing_creds/p_security_bprm_committing_creds.c
This works around the likely kernel bug discussed in #174.
A similar change has been CI-tested in a different branch, but let's wait for CI to be happy about this one.
> Workaround a CONFIG_KRETPROBE_ON_RETHOOK likely-bug in the kernel

- src/modules/exploit_detection/syscalls/exec/p_security_bprm_committed_creds/p_security_bprm_committed_creds.c
- src/modules/exploit_detection/syscalls/exec/p_security_bprm_committing_creds/p_security_bprm_committing_creds.c
- src/modules/exploit_detection/syscalls/exec/p_security_bprm_committing_creds/p_security_bprm_committing_creds.h
- src/modules/print_log/p_lkrg_debug_log.c
- src/modules/print_log/p_lkrg_print_log.h
In commit 9c5ef16cb51d51947c62e9116c6b52a3c3618bd0 we changed these
function to be untraceable. Respect that and remove them from
the list of traced functions.
This should address issue https://github.com/lkrg-org/lkrg/issues/176.
Building with debug flag and P_LKRG_STRONG_KPROBE_DEBUG enabled.
> debug: fix build with P_LKRG_STRONG_KPROBE_DEBUG

- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- .github/workflows/run-boot-tests.sh
- mkosi.build
Trigger loading of `vhost_vsock` module by the kernel, which uses UMH to call `modprobe`.
As a side effect copy (compiled) source tree into `/lkrg` of `mkosi` boot image. (This may be useful for manual testing.)
> CI: Run boot-tests script with UMH test

- .github/workflows/docker-boot.sh
- .github/workflows/docker-boot.yml
- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- .github/workflows/run-boot-tests.sh
- mkosi.build
Currently i386 and arm64v8. (I didn't find a way to create image for arm32v7 yet.)
x86_64 is just an example to prove it's working, since other arches are failing.
Perhaps we should delete x86_64 target.
And maybe we should delete arm64v8 either, it's slower than i386 and wasn't requested.
> CI: Use Docker to create bootable multi-arch images

- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.c
- src/modules/integrity_timer/p_integrity_timer.c
- src/p_lkrg_main.h
This commit brings a few important changes:
- LKRG has used to leverage SLAB_HWCACHE_ALIGN but memory overhead
may be too significant for LKRG's use cases
- Since the kernel 4.5+ we can use SLAB_ACCOUNT to make sure that
LKRG's caches are standalone
- Modify the size of pCFI stack buffer cache to be smaller and
decoupled from the PAGE_SIZE (there is no reason for that)
Additionally, this commit should help addressing #131
> Reduce memory overhead generated by kmem_cache_create

- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.h
Rework the version checking code for the variable length JUMP_LABEL feature and extend this version check for Linux 5.15.40+.
It seems as of right now only the 5.15.x branch received this backport.
Closes: #192
Patch was applied to LKRG 0.9.3 and built against Linux 5.15.50. System was booted in this configuration, "LKRG initialized successfully!" message was observed, and no detected STEXT memory block hash mismatches were observed.
> Enable variable length jump label backport for 5.15.40+, cleanup

- .github/workflows/builds.yml
- .github/workflows/cross.yml
- .github/workflows/docker-boot.yml
- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
- mkosi.default
Fix `mkosi boot (mainline)` build error, because of disk full. Increased `RootSize` +1G.
[ ALSO, while we at it, switched GA `ubuntu-20.04` -> `ubuntu-22.04`. Not tested and can undo if it fails here in this PR. But if it isn't why not switch to a shiny new env.  If failed I will make another PR later. ]
https://github.com/vt-alt/lkrg/actions/runs/2599988787
Fixes: https://github.com/lkrg-org/lkrg/issues/194
> CI: (mainline): Fix 'No space left on device' error

- CHANGES
- LICENSE
- README
- scripts/bootup/lkrg-bootup.sh
- scripts/bootup/openrc/lkrg
- scripts/bootup/openrc/lkrg-openrc.sh
introduce OpenRC bootup scripts
I've tested it by running
```console
```
```console
/etc/init.d/lkrg start &&
lsmod | grep lkrg &&
/etc/init.d/lkrg status &&
rc-update add lkrg boot &&
rc-update show | grep lkrg
```
```console
```
on OpenRC system ([funtoo linux](https://www.funtoo.org))
**update**
after gathering requirements in [this comment](https://github.com/lkrg-org/lkrg/pull/197#issuecomment-1175588110) I've additionally run
```console
N 3
1
p_lkrg                221184  0
```
```console
p_lkrg                221184  0
```
and ensured that `p_lkrg` module is not unloaded from the kernel on poweroff or reboot
> feat(scripts): support OpenRC init system

- scripts/copy-builtin.sh
Changes to the Makefile enabling debug builds of LKRG resulted in
the copy-builtin script producing an errant Makefile inside the
target kernel tree.
Address this by creating a SECURITY_LKRG_DEBUG Kconfig option in
the Kconfig file and copy/update the relevant Makefile stanza into
the in-tree Makefile manually (vs extracting it from the source
Makefile and modifying in-flight).
Testing:
Built in Arch chroot, verified prompt for new option and module
build in-tree.
> Adapt copy-builtin.sh script for LKRG debug option

- src/modules/comm_channel/p_comm_channel.c
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/integrity_timer/p_integrity_timer.c
This has several commits fixing 3 separate issues.
Tested logging of `interval` and `log_level` sysctl value changes on one system. Waited for CI to be happy (18 checks) on my fork.
> Assorted fixes related to the recent logging changes

- .github/workflows/cross.yml
- .github/workflows/mkosi-boot.yml
Impish is started to fail, because it's EOL'ed at July 14, 2022 (replaced with `jammy`). Hirsute is EOL'ed at January 20, 2022, but it started to fail only recently (removed).
Tested on GA in my fork.
> CI: Remove EOL'ed Ubuntu releases

- CHANGES
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.h
- src/modules/print_log/p_lkrg_print_log.h
This takes care of the jump label change backport to 5.10.133+ and hopefully would also take care of potential backports of that change to even older branches. While at it, also increase severity of alerts from `CRIT` to `EMERG`.
CI on my fork shows 16 successful, 1 in progress. Also installed on an old system (without the variable length jump labels).
> Support variable length jump labels also for 5.10.133+

- .github/workflows/codeql-analysis.yml
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/exploit_detection/syscalls/override/overlayfs/p_ovl_override_sync/p_ovl_override_sync.c
- src/modules/exploit_detection/syscalls/override/overlayfs/p_ovl_override_sync/p_ovl_override_sync.h
- src/modules/kmod/p_kmod_notifier.c
- src/modules/print_log/p_lkrg_debug_log.c
This simplifies the changes introduced in #217.
Built and loaded for/into a kernel where `ovl_dentry_is_whiteout` is expected. Saw the expected log messages (unchanged from before, except that the word `funcion` is dropped for consistency with other current LKRG messages) for the case of no `overlay` loaded yet. Did a `modprobe overlay`, found `ovl_dentry_is_whiteout` in `/sys/kernel/debug/kprobes/list`. Unloaded and reloaded LKRG (with `rmmod` and `insmod`), saw no messages about inability to hook `ovl_dentry_is_whiteout` that time, saw that it is hooked per `/sys/kernel/debug/kprobes/list`.
Did not test the logic beyond successful hooking of what's expected. That is, did not test the `off` count check code path in the hook.
Meanwhile, 12 successful and 6 in progress CI checks in my …
> Overlay cleanup

- mkosi.default
- mkosi.postinst
mkosi' "--boot-protocols is deprecated and has no effect anymore", thus do not assume we will be booting using grub/bios.
Fixes: https://github.com/lkrg-org/lkrg/issues/227
[Not fully tested locally — will see GA report here.]
> CI: mkosi: Do not assume grub is installed

- mkosi.postinst
For (non-grub) BLS boot - install generated by Dracut initrd into systemd-boot loader entry.
Man pages for curious details: systemd-boot(7), bootctl(1), kernel-install(8).
Link: https://github.com/lkrg-org/lkrg/pull/228#issuecomment-1235403740
Fixes: db42541 ("CI: mkosi: Do not assume grub is installed")
Only tested locally before push.
Using `kernel-install` is somewhat low-level'ish but it seems there's no more generic way.
ps. Curiously, this took 3 hours to investigate, produce best solution, and test.
> CI: mkosi: Restore loading LKRG module from initrd

- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
closes #230
added [OpenRC's `/lib/rc/sh/cgroup-release-agent.sh`](https://github.com/OpenRC/openrc/blob/9b08de926b0ea2fd95d5d9f8cb3463eb3cd72d02/sh/cgroup-release-agent.sh.in) to [`p_umh_global[]`](https://github.com/lkrg-org/lkrg/blob/b56b8758afa23053dc62e0b469b1c12955cb94dc/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c#L39)
as a regular user I've:
made sure that bug is reproducable
```console
sudo /etc/init.d/cupsd restart
sudo /etc/init.d/cupsd restart
sudo dmesg | tail | grep 'LKRG: ALERT: BLOCK: UMH'
```
unloaded lkrg module and checked if it's there:
```console
sudo /etc/init.d/lkrg stop
lsmod | grep lkrg
```
tried to reproduce again
```console
sudo /etc/init.d/cupsd restart
sudo /etc/init.d/cupsd restart
sudo dmesg | tail | grep 'LKRG: ALERT: …
```
> fix: umh - allow openrc cgroup release agent [#230]

- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/notifiers/p_notifiers.h
- src/p_lkrg_main.h
This avoids use of the deprecated and now dropped `get_random_int` on Linux 4.11+ (#233), simplifies our `get_random_long` wrapper (#234), and fixes a typo in one of the notifiers' rates (changing its rate to hopefully what was intended).
> Clean up our use/wrapper of get_random_int()/get_random_long()

- .github/workflows/docker-boot.yml
1. Re-enable AArch64 test in our GitHub Actions. The test had been introduced in #181, but promptly disabled since it was failing all the time because of our lack of support of BTI in our hackish calls to non-exported kernel functions, tracked as #183.
2. Now we bypass that issue by specifying to QEMU `-cpu cortex-a57` instead of `-cpu max`, so that we do test on AArch64 but without BTI. I got `-cpu cortex-a57` from https://wiki.ubuntu.com/ARM64/QEMU
3. We also switch to testing on Ubuntu Jammy instead of Ubuntu Impish, as the latter had been EOL'ed and is no longer downloadable (at least by this test as previously configured).
The testing is described in some detail in comments I added today to #181. In short, this test now passes in my fork, whereas a different test with only …
> CI: Re-enable AArch64 test, but without BTI

- src/modules/exploit_detection/p_exploit_detection.c
Since torvalds/linux@e9d75a0ba87851187fe52493f1527229a7e101b3 struct stackframe has been renamed to struct unwind_state for arm64.
> Add support for Kernel 5.19+ for aarch64

- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.h
Starting from RHEL8.6 4.18.0-372.32.1.el8_6 kernel struct text_poke_loc is not exported and we need to correctly take this into account. Previous RHEL8.6 kernels did not hide this structure so we need to find some ways to disinguish them. We do it in this commit and it should fix #236
Tested against the following RHEL8.6 kernels:
- 4.18.0-372.26.1.el8_6.x86_64 (the newest kernel for RHEL 8.6)
- 4.18.0-372.32.1.el8_6.x86_64
- 4.18.0-372.9.1.el8.x86_64 (the oldest kernel for RHEL 8.6)
> Add support for new RHEL8.6+ kernels

- src/modules/exploit_detection/p_exploit_detection.c
Fixes #240
We were only performing a check of `real_cred` conditionally - only if we had already detected another discrepancy. @Adam-pi3 and I couldn't recall a reason for this limitation, so I tried removing the condition, and things seem fine.
Our CI tests are happy (except RHEL8, which currently can't be tested - pending another fix). Also, no issues when installed in an old Fedora VM with some light usage.
> pINT: Make the real_cred check in p_cmp_tasks() unconditional

- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
Add /usr/libexec/abrt-hook-ccpp to UMH allow list. This program path is used on older Red Hat distros.
We're already allow-listing a couple of other pathnames for the same kind of functionality. Actually, this is dangerous non-essential functionality of those distros, which we could want to have LKRG optionally block - so maybe split them out into a separate optional allow list later.
Observed the below upon a program crash on older Fedora prior to this change:
```
[210464.280363] LKRG: ALERT: BLOCK: UMH: Executing program name /usr/libexec/abrt-hook-ccpp
[210464.281292] Core dump to |/usr/libexec/abrt-hook-ccpp 11 0 30372 1000 1000 1668011706 30372 30372 pipe failed
```
Added the path to our allow list. Didn't actually retest yet, but this got to work. ;-)
> UMH: Allow /usr/libexec/abrt-hook-ccpp for older Red Hat distros

- src/modules/wrap/p_struct_wrap.h
- src/p_lkrg_main.c
This commit fixes the race problem between 2+ concurrent sysctl updates. It is part of the work related to #204
The way how the fix is implemented is to move synchronization logic to the `p_lkrg_open/close_rw` interface. The main reason for that is because we use these API outside of sysctl interface as well. We need to synchronize to these usage as well. It makes more sense to have such synchronization logic there.
It is fine to wrap `proc_dointvec_minmax` around mutex and kernel does that as well:
https://elixir.bootlin.com/linux/latest/source/kernel/kprobes.c#L953
TODO: We should rework sysctl interface to reduce the window between the `p_lkrg_open/close_rw` calls. Currently, we do all the work between these calls, but we don't need to. We can call `p_lkrg_close_rw` as soon as we …
> Add synchronization logic around sysctl interface

- Makefile
- src/modules/integrity_timer/p_integrity_timer.c
- src/modules/integrity_timer/p_integrity_timer.h
- src/modules/integrity_timer/verify_kprobes/p_verify_kprobes.c
- src/modules/integrity_timer/verify_kprobes/p_verify_kprobes.h
- src/modules/wrap/p_struct_wrap.h
- src/p_lkrg_main.c
Add a new logic to the integrity verification routine verifying if the kprobes are enabled and correctly run.
This commit makes kprobe verification functionality as an independent module invoked by integrity verification routine as well as during initialization to make sure kprobes are enabled and run as intended (otherwise, initialization fails).
I've done a few tests:
- Manually disable kprobes before initialization (new feature correctly detects kprobes don't work)
- There is no problem when kprobes are enabled (verified the code-flow and debug messages that feature works and run as intended)
- Manually disable kprobes after initialization (new feature correctly detects kprobes don't work)
- There is no problem when kprobes are enabled (verified the code-flow and debug messages that …
> Add a kprobe verification functionality

- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
Main (and only) branch of mkosi is switching to a bleeding edge systemd tools which are not available on Ubuntu we are testing on. Instead of migrating off mkosi to something else, we can still use some previously wording tag such as `v14'.
Link: https://github.com/lkrg-org/lkrg/issues/253
> CI: Use latest usable mkosi v14

- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
Address #258 by adding /usr/bin/modprobe to the UMH allow-list.
Fixes booting on Arch Linux when LKRG is built into the kernel binary
Booted in an Arch Linux VM:
```sh
[root@svl-arch00 ~]# uname -r ; modinfo lkrg |head;sysctl -a|grep umh_
6.1.8
name:           lkrg
filename:       (builtin)
license:        GPL v2
file:           security/lkrg/lkrg
description:    pi3's Linux kernel Runtime Guard
author:         Adam 'pi3' Zabrocki (http://pi3.com.pl)
parm:           log_level:log_level [3 (issue) is default] (uint)
parm:           heartbeat:heartbeat [0 (don't print) is default] (uint)
parm:           block_modules:block_modules [0 (don't block) is default] (uint)
parm:           interval:interval [15 seconds is default] (uint)
lkrg.umh_enforce = 1
lkrg.umh_validate = 1
```
> Add UMH modprobe path for Arch Linux init context

- src/modules/exploit_detection/p_exploit_detection.c
Since kernel-5.14.0-248.el9 struct stackframe is renamed to struct unwind_state on aarch64.
> RHEL 9.2 5.14.0-248.el9 aarch64: rename stackframe to unwind_state

- src/modules/database/FTRACE/p_ftrace_modify_all_code/p_ftrace_modify_all_code.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/arch/p_arch_metadata.c
- src/modules/database/p_database.c
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/p_selinux_state.c
- src/modules/kmod/p_kmod.c
- src/p_lkrg_main.c
- src/p_lkrg_main.h
I simplified the usage of P_SYM_INIT by removing the second parameter - type declaration. I think this is unnecessary because type declaration is done during variable definition, not during variable initialization.
I compiled it successfully on Ubuntu 22.04 and did not encounter any errors when running it.
> Simplify the use of P_SYM_INIT()

- README
- scripts/bootup/lkrg-bootup.sh
- scripts/bootup/openrc/lkrg-openrc.sh
- scripts/bootup/systemd/lkrg-systemd.sh
For my use case it happened that I ran the install scripts not from the root of the project (and not through make). I noticed that they fail "silently" in that case. I thought it would not hurt to update the scripts to be more self-sufficient, i.e., independent of the cwd and with some usage and root checks.
Tested that it works as expected for systemd, cannot say anything about the openrc part.
> make bootup scripts independent of cwd, add usage and root checks

- src/modules/comm_channel/p_comm_channel.c
This is needed for post-6.4 kernels. Briefly tested manually on a couple of systems - way outdated CentOS 7 and AlmaLinux 8.5. CI is happy under my personal GitHub account, so should probably be here as well.
Fixes #280
> Stop using register_sysctl_table()

- .github/workflows/mkosi-mainline.yml
Mkosi's own dracut hook, which is triggered from `dpkg -i`, calls `dpkg-reconfigure` causing dpkg frontend lock conflict. But `initrd.img` is generated correctly. Workaround by ignoring `dpkg-reconfigure` errors in the hook.
dpkg: error: dpkg frontend lock was locked by another process with pid 5
Note: removing the lock file is always wrong, can damage the locked area
and the entire system. See <https://wiki.debian.org/Teams/Dpkg/FAQ#db-lock>.
run-parts: /etc/kernel/postinst.d/zz-systemd-boot exited with return code 2
Link: https://github.com/lkrg-org/lkrg/issues/283
I did not investigate thoroughly all internal workings of `dpkg -i`/`dpkg-reconfigure` and what is changed since last week in Ubuntu (old action logs are not enough to clarify this.)
Locally.
> CI: mkosi-mainline: Workaround 'dpkg: error: dpkg frontend lock'

- .github/workflows/builds.yml
`opensuse/tumbleweed` requires `awk` and docker hub images are deprecated.
On my fork.
> CI: Update openSUSE docker builds

- .github/workflows/builds.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cross.yml
- .github/workflows/docker-boot.yml
- .github/workflows/mkosi-boot.yml
- .github/workflows/mkosi-mainline.yml
This should quiet the warning:
> The following actions uses node12 which is deprecated and will be  forced to run on node16: actions/checkout@v2. For more info:  https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> CI: Update workflows to use latest versions of the actions

- mkosi.default
Ubuntu removed 'systemd-gpt-auto-generator' from systemd_253.5-1ubuntu5, causing dracut to be unable to find the root partition without assistance. It appears that specifying the root label could be a good solution.
Fixes: https://github.com/lkrg-org/lkrg/issues/287
Will be tested in this PR.
> CI: mkosi: Fix mainline boot on Ubuntu mantic

- .github/workflows/ubuntu-kernel-daily.sh
https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/ reporting:
```
<title>301 Moved Permanently</title>
<p>The document has moved <a
href="https://kernel.ubuntu.com/mainline/daily/">here</a>.</p>
```
Fixes: https://github.com/lkrg-org/lkrg/issues/292
Base url changed.
Will be tested in this PR.
> CI: mainline: Change base URL

- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.h
A new 'text_poke_loc' was backported to RHEL 8.8+. This commit brings the support for such kernels as well as addresses the #295 problem.
Tested on RHEL 9.1 (Alma), RHEL 9.0 (Alma), RHEL 8.7 (Alma), RHEL 8.8 (Alma) and RHEL 8.3 (CentOS)
> Add support for RHEL 8.8

- .github/workflows/mkosi-mainline.yml
Ubuntu started to create mainline kernel packages for upcoming 'noble' release but jammy's (where CI runs) debootstrap knows nothing about it.
debootstrap fails with (though this is not visible in mkosi output):
E: No such script: /usr/share/debootstrap/scripts/noble
Add Ubuntu's development debootstrap from their git. It's possible to run it from the git repo itself (as stated in their README). The repo cloned into `/debootstrap` so we don't need to set `DEBOOTSTRAP_DIR` and executable is symlinked to `/usr/local/bin` which we prepared earlier (and GA prepends it to `PATH`).
For the current bug it's not required to symlink `debootstrap` script because today we only need to update their `scripts` directory but this fuller update may be future proof.
Fixes: …
> CI: mkosi-mainline: Support for 'noble' mainline kernels

- .github/workflows/docker-boot.sh
Ubuntu starts to install linux-headers-generic
(linux-headers-5.15.0-102-generic) with /lib/modules/5.15.0-102-generic containing the `build` link, which confuses simple `ls` method version detection and later depmod call. Make kernel version detection similar to the other places.
Fixes: https://github.com/lkrg-org/lkrg/issues/332
https://github.com/vt-alt/lkrg/actions/runs/8747621184/job/24006360510
> ci: docker-boot: Improve detection of kernel version

- mkosi.default
Installing dkms should be generic enough to bring everything needed to build kernel modules.
This is not 100% solution since exact kernel version may still differ:
$ make ...
The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-3ubuntu1) 13.3.0
You are using:           gcc-13 (Ubuntu 13.3.0-4ubuntu1) 13.3.0
But this is best effort.
Tested on my GA account.
> CI: mkosi: Fix the lack of gcc-13 for mainline builds

- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/syscalls/p_seccomp/p_seccomp.c
- src/modules/exploit_detection/syscalls/p_seccomp/p_seccomp.h
Starting from kernel 5.9+ function 'put_seccomp_filter' has been inlined and unavailable for hooking. However, internal not-inline function was used to mitigate the problem. Unfortunately, there is no equivalent counter-part function for new hook and the old one looks incompatible which we overlooked. This patch is switching the logic for kernels 5.9+ to custom implementation of refcount logic and it should address the issue reported as #338
Verified on AlmaLinux 8.8 (4.18.0-477.27.2.el8_8.x86_64) and Ubuntu 22.04.4 LTS (6.3.0-060300-generic). Likely more comprehensive tests are needed.
> [Seccomp] Switch to refcount logic for kernels >= 5.9

- debian/control
According to Debian packaging guidelines, 'dh-dkms' should be added to the build dependencies.
Link: https://github.com/linuxdeepin/developer-center/issues/10661
> fix: debian/control: Add build-depends dh-dkms

- .github/workflows/cross.yml
- .github/workflows/docker-boot.sh
- .github/workflows/docker-boot.yml
Docker now seems to require specifying the platform for ARM. But add it for 386 too to make configuration generic.
Fixes: https://github.com/lkrg-org/lkrg/issues/356
GA
> CI: Fix Docker multi-platform builds

- .github/workflows/builds.yml
- .github/workflows/cross.yml
Fix CI for Centos 7 and ALT Sisyphus.
- Centos fix on my GA. 
- It seems that flt.altlinux.org have 1 day delay behind actual repo. Thus, the fix will start to work after 24 hours.
> CI fixes for Centos 7 and ALT Sisyphus

- CHANGES
- src/modules/comm_channel/p_comm_channel.c
- src/modules/database/CPU.c
- src/modules/database/arch/x86/p_switch_idt/p_switch_idt.c
- src/modules/integrity_timer/p_integrity_timer.c
- src/modules/integrity_timer/p_integrity_timer.h
- src/modules/kmod/p_kmod_notifier.c
and acquire the lock for writing on lkrg.msr_validate changes, which affect whether MSRs are included in the computed hash value.
Fixes #370
I am testing with:
```shell
while :; do sysctl lkrg.msr_validate=1; sysctl lkrg.msr_validate=0; done
```
I also trigger some coredumps in a loop, as this was causing softlocks with my previous attempts at fixing this issue (when I tried acquiring `p_db_lock`).
> Move the CPU metadata dumping under a new config read lock

- src/modules/exploit_detection/ed_task_tree.c
- src/modules/exploit_detection/p_exploit_detection.c
This fixes #378.
The first commit here I tested by re-running the tests I mentioned in #378. The second commit is untested yet, I'll test it in the same way now.
> Fix ed_task_cache cleanup on failed LKRG initialization

- CHANGES
- src/modules/integrity_timer/verify_kprobes/p_verify_kprobes.c
- src/p_lkrg_main.c
Works around #364 seen on recent Gentoo.
This turns inability to hook the dummy function from FATAL to ISSUE, and lets LKRG loading proceed without kprobes testing.
As I was unable to reproduce the original issue, I simulated it by temporarily renaming the function attempted to be hooked. I enabled `log_level=4` and confirmed that the log records are as expected for both being able to hook (and use) the function and otherwise (when I rename it).
> Make kprobes testing via LKRG's own dummy function hooking optional

- CHANGES
- src/modules/exploit_detection/p_exploit_detection.c
Fixes #375
A comment in <linux/nsproxy.h> documents "the namespaces access rules", which allow reading current task's namespaces without precautions, but another task's with task_lock() and check for "nsproxy != NULL".  We also worry about potential deadlocks, so we use spin_trylock() instead and skip our namespace validation if we couldn't acquire a lock.  We do the same on update and validation.
With this command, which previously triggered the issue and now does not (so far):
```
while :; do sysctl lkrg.trigger=1; sysctl lkrg.msr_validate=0; sysctl lkrg.trigger=1; sysctl lkrg.msr_validate=1; dmesg | tail -100 | fgrep -v LKRG; done
```
also by adding this hack:
```c
if (uid_eq(p_orig->p_ed_task.p_cred.euid, KUIDT_INIT(666))) p_orig->p_ed_task.p_ns.net_ns++;
```
and making sure this …
> Fix race condition (possible NULL dereference) with namespace validation

- CHANGES
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/syscalls/override/p_override_creds/p_override_creds.c
- src/modules/exploit_detection/syscalls/override/p_override_creds/p_override_creds.h
- src/modules/exploit_detection/syscalls/override/p_revert_creds/p_revert_creds.c
- src/modules/exploit_detection/syscalls/override/p_revert_creds/p_revert_creds.h
This works by not validating the effective credentials when the pointer differs, which may indicate that override_creds() is in effect or that the pointer was overwritten in an attack.  So with this workaround we'll be blind to cred pointer overwrite attacks, but would still detect overwrites of the creds themselves if the pointer is kept intact.  We should also still detect exploits' use of commit_creds() as that function also replaces real_cred, which we continue to validate in all cases.
Works around #371
On Arch Linux with 6.14.3-arch1-1, running SUID programs such as `su` and `passwd` on the Arch system itself, as well as in a Docker container with Alpine Linux. Without the relaxed validation, all of these triggered alerts and the commands were killed. With this PR's changes, they …
> Support new kernels without hook-able {override,revert}_creds()

- src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
Allow `off` to be set a second time. First from our hook of `call_usermodehelper_exec_async` and then also from our hook of `security_bprm_committing_creds`.  Without this hack, the latter would falsely detect `off` flag corruption due to our "`off` most be off" check.
Works around #385
By multiple reboots of the bare metal system where the issue was almost reliably reproducible. With this change, the issue is not seen on that system anymore.
> UMH: Allow "off" to be set a second time

- .github/workflows/docker-boot.yml
- .github/workflows/fedora-mainline.yml
- .github/workflows/run-boot-tests.sh
- Makefile
Build (in `fedora:rawhide` docker image) for mainline kernels and quick boot using qemu-kvm over 9pfs mount and direct kernel & initrd binaries. Not the full system boot simulation like previous mkosi workflow used.
Tested in my GA fork.
This took 2 days.
> CI: Fedora mainline build & boot

- CHANGES
- src/modules/database/CPU.c
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/integrity_timer/p_integrity_timer.c
- src/modules/integrity_timer/verify_kprobes/p_verify_kprobes.c
Two changes/commits here:
1. Wrap integrity violation checks in unlikely() - this is just something I happened to start working on while implementing the more important change:
2. Compensate for the relaxed cred pointer checks in p_cmp_tasks() especially on 6.13+ by stricter checks in places where we also assert that our `off` flag must be off. This corresponds to a subset of our hooks where no creds override is expected. We may later expand these checks to more places. See #371
In the VM where/while I worked on completing these changes, and in our CI under my personal GitHub account.
> Perform stricter cred pointer checks where no creds override is expected

- README
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.h
- src/modules/database/arch/p_arch_metadata.c
- src/modules/wrap/p_struct_wrap.h
- src/p_lkrg_main.h
This fixes issues identified in our CI setup when building for and loading into 6.16-rc kernels. Currently 3 separate issues were identified and are (attempted to be) fixed, as described in #396.
In my development VM with an older kernel, and also via our CI jobs (let's see what they say now).
> Support 6.16-rc, fix JUMP_LABEL batch indexing in hook of arch_jump_label_transform_apply

- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/exploit_detection/syscalls/exec/p_security_bprm_committed_creds/p_security_bprm_committed_creds.c
1. Resetting `off` was wrong during seccomp sync. Let's never do that. Fixes #388.
2. The `off` override during seccomp sync isn't the same as creds override, and no creds override is expected where we call the non-override form of `p_set_ed_process_on` / `p_set_ed_process_off`. So let's perform the creds pointer checks added in #394 even during seccomp sync.
The first change was tested for a while in my development VM. Both changes together are tested in our CI setup. I'll test these some more before merging.
> Never reset "off", check cred pointers even during seccomp sync

- .github/workflows/mkosi-boot.yml
- CHANGES
- README
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/exploit_detection/p_exploit_detection.h
- src/modules/self-defense/hiding/p_hiding.h
This fixes #374 and simplifies things at the same time. It also adds more Ubuntu CI jobs, and fixes #406.
In our CI setup and in my dev VM. I haven't yet tested that credentials overwrite detection still works after these changes - I will before merging this.
> pINT: No longer store/validate override creds

- .github/workflows/builds.yml
Use supposedly more robust install method.
Fixes: https://github.com/lkrg-org/lkrg/issues/410
GA.
> CI: Replace unreliable kernel package targets for alt:sisyphus

- CHANGES
- src/modules/database/FTRACE/p_ftrace_modify_all_code/p_ftrace_modify_all_code.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
- src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
- src/modules/database/TRACEPOINT/p_arch_static_call_transform/p_arch_static_call_transform.c
- src/modules/database/p_database.c
- src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
- src/modules/exploit_detection/p_exploit_detection.c
- src/modules/integrity_timer/p_integrity_timer.c
- src/modules/ksyms/p_resolve_ksym.c
- src/modules/wrap/p_struct_wrap.h
- src/p_lkrg_main.c
- src/p_lkrg_main.h
Fixes #413
Initial hack to workaround Intel CET IBT.
In our CI and in an Arch Linux VM, and also by forcing this code to be compiled in and/or running on other x86_64 systems (even without IBT support in the kernel). We do not currently know whether it actually solves the problem, but it should.
After proper testing, next steps may be making it more reliable (not depending on compiler specifics so much, as mentioned in the lengthy source code comment) and/or implementing a similar trick for ARM BTI.
> Intel CET IBT support

- src/p_lkrg_main.c
- src/p_lkrg_main.h
If we don't explicitly specify section alignment, then perhaps an existing section is page-aligned or not just as well, so our page-alignment of a symbol within that section will work or fail just as well.
Fixes #158
LKRG built and loaded cleanly in my dev VM. I've also confirmed that our sysctl settings _are_ read-only in such build, by temporarily removing a pair of calls like this:
```diff
+++ b/src/modules/comm_channel/p_comm_channel.c
@@ -477,14 +477,14 @@ static int p_sysctl_interval(P_STRUCT_CTL_TABLE *p_table, int p_write,
unsigned int p_tmp;
p_tmp = P_CTRL(p_interval);
-   p_lkrg_open_rw();
+//   p_lkrg_open_rw();
if ( (p_ret = proc_dointvec_minmax(p_table, p_write, p_buffer, p_len, p_pos)) == 0 && p_write) {
if (P_CTRL(p_interval) != p_tmp) {
p_print_log(P_LOG_STATE, "Changing …
```
> Drop section .p_lkrg_read_only

- src/modules/exploit_detection/p_exploit_detection.c
Fixes #408
This allows a task's current seccomp mode to be `SECCOMP_MODE_DEAD`, which happens when the task is exiting.
It weakens our detection slightly as an exploit could set this mode and go undetected by LKRG, but doing so would instead trigger the kernel itself to detect this soon and do:
```c
/* Surviving SECCOMP_RET_KILL_* must be proactively impossible. */
case SECCOMP_MODE_DEAD:
WARN_ON_ONCE(1);
do_exit(SIGKILL);
return -1;
```
So an exploit doing this doesn't appear to achieve anything - not a bypass, but task killed.
On my dev VM and in our CI setup. Reproducing the original issue took a couple of months, so I'm not waiting for that, and we do not have a test case developed specifically to trigger this quickly.
> pINT: Allow SECCOMP_MODE_DEAD

- CHANGES
- src/p_lkrg_main.h
Fixes #259
This extends #415 to also support clang, based on testing by @0xC0ncord in #259.
So far only directly tested in my dev VM and in our CI setup with gcc. I don't test with clang. But the approach is similar to what @0xC0ncord had kindly tested for us (currently running into other and likely unrelated issues with hardened/optimized kernels and clang, so I think this part is ready for a PR).
We may also need to complete and merge #419 to support clang builds.
> Support Intel CET IBT also with clang, and support KCFI (clang CFI)

- src/modules/exploit_detection/syscalls/override/overlayfs/p_ovl_override_sync/p_ovl_override_sync.h
- src/modules/kmod/p_kmod.h
- src/modules/kmod/p_kmod_notifier.c
We can't/don't hook override/revert_creds() on 6.13+, so we also don't need to hook anything OverlayFS on those kernels.
Fixes #426
In my dev VM (pre-6.13 kernel), in an Arch Linux VM with 6.14+ and a Docker container, and in our CI setup.
> Don't hook anything OverlayFS on 6.13+

- src/modules/exploit_detection/p_exploit_detection.c
Fixes #430
1. Drop all uses of `get_cred` / `put_cred`.
2. Add `rcu_read_lock` / `rcu_read_unlock` to `p_cmp_tasks`, even though the callers either already have those (for other reasons) or are for the current task.
3. Drop the only remaining use of `get_task_struct`.
4. Drop two memory barriers.
Light testing in my dev VM, and by our CI.
The first commit also got ~3 hours of stress-testing on the system where I previously saw #430 (not triggering it anymore), which now continues to stress-tests all 3 commits.
> pINT: Do not misuse get_cred(), get_task_struct(), memory barriers
